# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestopenbaidu():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testopenbaidu(self):
    self.driver.get("https://www.baidu.com/")
    self.driver.set_window_size(1024, 692)
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "kw").send_keys("hahah")
    self.driver.find_element(By.ID, "su").click()
  
